In [28]:
import torch
import numpy as np
from python_files.variable_maxpool_layer import var_maxpool
import math
from python_files.spatial_pyramidal_pooling import spatial_pyramid_pool

device = (
    "cuda"
    if torch.cuda.is_available()
    else "cpu"
)

In [32]:
# To get tensors, use torch.from_numpy()

array = np.array(
    [
    [[1,2,3,4,5,6,7,8,9],
    [11,12,13,14,15,16,17,18,19],],
    
    [[21,22,23,24,25,26,27,28,29],
    [31,32,33,34,35,36,37,38,39],],
    ])

array2 = np.array(
    [
    [[1,2,3,4,5,6,7,8,9, 40, 41,],
    [11,12,13,14,15,16,17,18,19, 50, 51],],
    
    [[21,22,23,24,25,26,27,28,29, 60, 61],
    [31,32,33,34,35,36,37,38,39, 70, 71],],
    ])

array3 = np.array(
    [
    [[1,2,3,4,5,6,7,8,9, 40, 41,],
    [11,12,13,14,15,16,17,18,19, 50, 51],],
    
    [[21,22,23,24,25,26,27,28,29, 60, 61],
    [31,32,33,34,35,36,37,38,39, 70, 71],],
    ])


torcharray = torch.from_numpy(array).to(device=device, dtype=torch.float)
torcharray2 = torch.from_numpy(array2).to(device=device, dtype=torch.float)

Conv1D_dept = torch.nn.Conv1d(in_channels=2, out_channels=2, kernel_size= 2, stride=1, padding=0, bias=False, device = device,)
Conv1D_pointwise = torch.nn.Conv1d(in_channels=2, out_channels=3, kernel_size= 2, stride=1, padding=0, bias=False, device = device)

In [31]:
spatial_pool1 = spatial_pyramid_pool(torcharray, (3,2,1), padding_front=True)

spatial_pool1

tensor([[ 3.,  6.,  9., 13., 16., 19.,  5.,  9., 15., 19.,  9., 19.],
        [23., 26., 29., 33., 36., 39., 25., 29., 35., 39., 29., 39.]],
       device='cuda:0')

In [35]:
spatial_pool2 = spatial_pyramid_pool(torcharray2, (3,2,1), padding_front=True)

spatial_pool2.requires_grad

False

In [36]:
conv_out = Conv1D_dept(torcharray2)
print(conv_out)

spatial_pool3 = spatial_pyramid_pool(conv_out, (3,2,1), padding_front=True)

spatial_pool3

tensor([[[  4.8861,   5.5349,   6.1837,   6.8325,   7.4812,   8.1300,   8.7788,
            9.4275,  24.9983,  30.1881],
         [ -1.0049,  -1.3939,  -1.7830,  -2.1720,  -2.5611,  -2.9502,  -3.3392,
           -3.7283, -11.5144, -16.1781]],

        [[ 17.8615,  18.5103,  19.1591,  19.8078,  20.4566,  21.1054,  21.7541,
           22.4029,  37.9737,  43.1635],
         [ -8.7860,  -9.1751,  -9.5642,  -9.9532, -10.3423, -10.7313, -11.1204,
          -11.5094, -19.2955, -23.9593]]], device='cuda:0',
       grad_fn=<ConvolutionBackward0>)


tensor([[  6.8325,   9.4275,  30.1881,  -1.0049,  -2.5611, -11.5144,   7.4812,
          30.1881,  -1.0049,  -2.9502,  30.1881,  -1.0049],
        [ 19.8078,  22.4029,  43.1635,  -8.7860, -10.3423, -19.2955,  20.4566,
          43.1635,  -8.7860, -10.7313,  43.1635,  -8.7860]], device='cuda:0',
       grad_fn=<CatBackward0>)